
package it.sapienza.softeng.soap.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapWebService", targetNamespace = "http://ws.soap.softeng.sapienza.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns it.sapienza.softeng.soap.ws.Director
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDirector", targetNamespace = "http://ws.soap.softeng.sapienza.it/", className = "it.sapienza.softeng.soap.ws.GetDirector")
    @ResponseWrapper(localName = "getDirectorResponse", targetNamespace = "http://ws.soap.softeng.sapienza.it/", className = "it.sapienza.softeng.soap.ws.GetDirectorResponse")
    public Director getDirector(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setMovie", targetNamespace = "http://ws.soap.softeng.sapienza.it/", className = "it.sapienza.softeng.soap.ws.SetMovie")
    @ResponseWrapper(localName = "setMovieResponse", targetNamespace = "http://ws.soap.softeng.sapienza.it/", className = "it.sapienza.softeng.soap.ws.SetMovieResponse")
    public void setMovie(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDirector", targetNamespace = "http://ws.soap.softeng.sapienza.it/", className = "it.sapienza.softeng.soap.ws.SetDirector")
    @ResponseWrapper(localName = "setDirectorResponse", targetNamespace = "http://ws.soap.softeng.sapienza.it/", className = "it.sapienza.softeng.soap.ws.SetDirectorResponse")
    public void setDirector(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns it.sapienza.softeng.soap.ws.Movie
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMovie", targetNamespace = "http://ws.soap.softeng.sapienza.it/", className = "it.sapienza.softeng.soap.ws.GetMovie")
    @ResponseWrapper(localName = "getMovieResponse", targetNamespace = "http://ws.soap.softeng.sapienza.it/", className = "it.sapienza.softeng.soap.ws.GetMovieResponse")
    public Movie getMovie(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<it.sapienza.softeng.soap.ws.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMovies", targetNamespace = "http://ws.soap.softeng.sapienza.it/", className = "it.sapienza.softeng.soap.ws.GetMovies")
    @ResponseWrapper(localName = "getMoviesResponse", targetNamespace = "http://ws.soap.softeng.sapienza.it/", className = "it.sapienza.softeng.soap.ws.GetMoviesResponse")
    public List<Movie> getMovies();

}
